apiVersion: v1
kind: Pod
metadata:
  name: gce-volume
  namespace: prod
spec:
  volumes:
  - name: mongodb-data
    gcePersistentDisk:
      pdName: mongodb
      fsType: ext4
  containers:
  - name: mongodb
    image: mongo
    ports:
    - containerPort: 27017
      protocol: TCP
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
