apiVersion: v1
kind: Pod
metadata:
  name: volume
  namespace: prod
spec:
  containers:
  - image: nginx:alpine
    name: git-volume
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: git
      mountPath: /usr/share/nginx/html
      readOnly: true 
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.0.1
    args:
      - "-repo=https://github.com/RakeshOrg1/kubia-website-example.git"
      - "-branch=master"
      - "-depth=1"
      - "-max-sync-failures=-1"
      - "-root=/templates"
      - "-dest=from-github"
      - "-wait=60"
      - "-ssh=true"
    volumeMounts:
    - name: git
      mountPath: /tmp/share/nginx/html
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/RakeshOrg1/kubia-website-example.git
    - name: GIT_SYNC_DEST
      value: git-sync
  volumes:
  - name: git
    gitRepo:
      repository:  https://github.com/RakeshOrg1/kubia-website-example.git
      revision: master
      directory: .
