apiVersion: v1
kind: Pod
metadata: 
  name: podders
spec:
  volumes:
  - name: mongodb
    persistentVolumeClaim:
      claimName: mongo-pvc
  containers:
  - image: mongo
    name: mamaammamiya
    ports:
    - containerPort: 27017
      protocol: TCP
    volumeMounts:
    - name: mongodb
      mountPath: /data/db


