apiVersion: v1
kind: Pod
metadata:
  name: edpod
  namespace: prod
spec:
   containers: 
   - name: html-gen
     image: luksa/fortune
     volumeMounts:
     - name: edkubia
       mountPath: /var/htdocs
   - name: nginx
     image: nginx:alpine
     volumeMounts:
     - name: edkubia
       mountPath: /usr/share/nginx/html
       readOnly: true
     ports:
     - containerPort: 80
       protocol: TCP
   volumes:      
   - name: edkubia
     emptyDir: {}
