apiVersion: v1
kind: Pod
metadata:
  name: hostpath
  namespace: prod
spec:
  containers:
  - name: hspod
    image: nginx:alpine
    ports:
    - containerPort: 8080
      protocol: TCP  
    volumeMounts:
    - name: hsmount
      mountPath: /usr/share/nginx/html
  volumes:
  - name: hsmount
    hostPath:
      type: Directory
      path: /var/logs/      
