---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs5
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: pods
      namespace: prod
      labels:
        name: nginx
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs6
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx1
  template:
    metadata:
      name: pods
      namespace: prod
      labels:
        name: nginx1
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: kutia
  namespace: prod
spec:
  ingressClassName: nginx-example1
  rules:
  - host: haricloudsolutions.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc4 
            port:
              number: 80
  - host: haricloudsolutions.live
    http:
      paths:
      - path: /me
        pathType: Prefix
        backend:
          service:
            name: svc6
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc4
  namespace: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30124
  selector:
    name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc6
  namespace: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30126
  selector:
    name: nginx1
