apiVersion: batch/v1
kind: Job
metadata: 
  name: job1
  namespace: prod
spec:
  template:
    metadata:
      name: pod
    spec:
      containers: 
      - image: luksa/batch-job
        name: cont1
        ports:
        - containerPort: 8080
          protocol: TCP
      #restart Policy is not set , this yaml file will throw energy


