apiVersion: v1
kind: Pod
metadata: 
  name: psv1
  namespace: prod
spec:
  volumes:
  - name: psv-data
    gcePersistentDisk:
      pdName: mongodb
      fsType: ext4
  containers:
  - name: psv-12
    image: mongo
    volumeMounts:
    - name: psv-data
      mountPath: /data/db/
    ports:
    - containerPort: 80
      protocol: TCP    
