apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: kubia1
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      name: kubia
      labels:
        app: prod
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
        ports:
        - containerPort: 8080
          protocol: TCP

