apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia1
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kubia1
  template:
    metadata:
      labels:
        name: kubia1
    spec:
      containers:
      - name: kubia12
        image: luksa/kubia
        ports:
        - containerPort: 80
          protocol: TCP    
