apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-vol1
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/ngnix/html
      readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/TeamTestEngineers/kubia-website-example.git
      revision: master
      directory: .



