---
apiVersion: v1
kind: Service
metadata:
  name: svc3
  namespace: prod
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    name: rake

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs3
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: rake
  template:
    metadata:
      labels:
        name: rake
    spec:
      containers:
      - image: luksa/kubia
        name: rake
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443

