---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: asia:south1-a  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mongodb-pvc
spec:
 resources:
   requests:
     storage: 1Gi
 accessModes:
 - ReadWriteOnce
storageClassName: "fast"  
