---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: rollingUpdate
  template:
    metadata: 
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: numerouno51/kubia:v1
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fin
spec:
  type: NodePort
  selector:
    app: kubia
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30666

