apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - name: fortunev2
    image: suryasbg/v2
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval  
