apiVersion: v1
kind: Pod
metadata: 
   name: confi
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: fortune
    image: suryasbg/forntune.img
    args: ["6"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs    
