apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs1
  namespace: prod
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      namespace: prod
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 80
          protocol: TCP    
