apiVersion: v1
kind: Pod
metadata: 
  name: kubia-manaul1
  labels:
    env: test1
    region: India
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP 
