apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds1
  namespace: prod
spec:
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: kubia3
        image: luksa/kubia
        ports:
        - containerPort: 8080
          protocol: TCP 
